version: "3.6"

services:
  postgres:
    container_name: "db"
    image: "postgres:12"
    environment:
      - POSTGRES_PASSWORD=AcrediteNoCodigo
    ports:
    - "5433:5432"
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
    - db:/var/lib/postgresql/data
volumes:
  db:
